version: '3.7'

services:
  api:
    container_name: api
    build:
      context: ../packages/APIService
      target: development
    volumes:
      - "../packages/APIService:/usr/src/api"
      - "/usr/src/api/node_modules"
    ports:
      - 3000:3000
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - redis
  micro:
    container_name: micro
    build:
      context: ../packages/MicroService
      target: development
    volumes:
      - ../packages/MicroService:/usr/src/micro
      - /usr/src/micro/node_modules
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - redis
  redis:
    container_name: redis
    image: redis
    networks:
      - webnet
networks:
  webnet:
volumes:
  pgdata:
