version: '3.7'

services:
  api:
    container_name: api
    build:
      context: ../packages/APIService
      target: development
    volumes:
      - .:/usr/src/api
      - /usr/src/api/node_modules
    ports:
    #   - ${SERVER_PORT}:${SERVER_PORT}
      - 3000:3000
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - redis
  micro:
    container_name: micro
    build:
      context: ../packages/MicroService
      target: development
    volumes:
      - .:/usr/src/micro
      - /usr/src/micro/node_modules
    ports:
    #   - ${SERVER_PORT}:${SERVER_PORT}
      - 3001:3001
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - redis
  redis:
    container_name: redis
    image: redis:5
    networks:
      - webnet
networks:
  webnet:
volumes:
  pgdata: